editor/urls.py
from django.urls import path
from . import views

app_name = 'editor'
urlpatterns = [
    path('', views.IndexView.as_view(), name='index'),
    path('<int:pk>/', views.DetailView.as_view(), name='detail'),
    path('<int:pk>/results/', views.ResultsView.as_view(), name='results'),
    path('<int:pixel_posicao>/colorir/', views.colorir, name='colorir'),
]

pixel_django/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('', include('editor.urls')),
    path('admin/', admin.site.urls),
]

editor/models.py
import datetime

from django.contrib import admin
from django.db import models
from django.utils import timezone

# Create your models here.
class Pixel(models.Model):
  posicao = models.IntegerField(default=0)
  cor = models.CharField(max_length=7)

  def __str__(self):
    return str(self.posicao)

editor/views.py
from django.http import HttpResponseRedirect
from django.shortcuts import get_object_or_404, render
from django.urls import reverse
from django.utils import timezone
from django.views import generic

from .models import Pixel

# Create your views here.
class IndexView(generic.ListView):
    template_name = 'editor/index.html'
    context_object_name = 'pixels_list'

    def get_queryset(self):
        """
        Retorna os pixels criados
        """
        return Pixel.objects.all()

class DetailView(generic.DetailView):
    model = Pixel
    template_name = 'editor/detail.html'

class ResultsView(generic.DetailView):
    model = Pixel
    template_name = 'editor/results.html'

def colorir(request, pixel_posicao):
    pixel = get_object_or_404(Pixel, pk=pixel_posicao)
    opcao = request.POST['cor']
        
    pixel.cor = opcao
    pixel.save()

    # Always return an HttpResponseRedirect after successfully dealing
    # with POST data. This prevents data from being posted twice if a
    # user hits the Back button.
    return HttpResponseRedirect(reverse('editor:index'))

editor/templates/editor/detail.html
{% load static %}

<link rel="stylesheet" type="text/css" href="{% static 'editor/style.css' %}">

<main>
    <h1>pixel {{ pixel.posicao }}</h1>
    <h3>atual: <span style="color:{{ pixel.cor }}">{{ pixel.cor }}</span></h3>

    <form action="{% url 'editor:colorir' pixel.posicao %}" method="post">
    {% csrf_token %}
    <fieldset>
        <legend><h3>nova cor:</h3></legend>
        {% if error_message %}<p><strong>{{ error_message }}</strong></p>{% endif %}

        <input type="color" name="cor" id="cor-pixel" value="{{ pixel.cor }}">

    </fieldset>
    <input type="submit" value="confirmar">
    </form>

    <a href="./..">Voltar pro grid?</a>
</main>

editor/templates/editor/index.html
{% load static %}

<link rel="stylesheet" type="text/css" href="{% static 'editor/style.css' %}">

{% if pixels_list %}
  <main>
    {% for pixel in pixels_list %}
    <div class="popup" onclick="myFunction({{ pixel.posicao }})">
      <svg>

          <rect style="fill:{{ pixel.cor }}" />

      </svg>
      <div class="popuptext" id="myPopup{{ pixel.posicao }}">

        <form action="{% url 'editor:colorir' pixel.posicao %}" method="post">
        {% csrf_token %}
        <fieldset>
          <legend><h3>nova cor:</h3></legend>
          {% if error_message %}<p><strong>{{ error_message }}</strong></p>{% endif %}

          <input type="color" name="cor" id="cor-pixel" value="{{ pixel.cor }}">

        </fieldset>
        <input type="submit" value="confirmar">
        </form>

      </div>
    </div>
    {% endfor %}
  </main>

{% else %}
    <p>Nenhum pixel criado.</p>
{% endif %}

<script>
  // When the user clicks on div, open the popup
  function myFunction(pos) {
    let tchau = document.getElementsByClassName("show");
    for (i = 0; i < tchau.length; i++) {
      tchau[i].classList.remove("show")
    }
    var popup = document.getElementById("myPopup" + pos);
    popup.classList.toggle("show");
  }
  
</script>

editor/templates/editor/results.html
{% load static %}

<link rel="stylesheet" type="text/css" href="{% static 'editor/style.css' %}">

<main>
  <h1>pixel {{ pixel.posicao }}</h1>

  <svg>
    <rect style="fill:{{ pixel.cor }}" />
  </svg>

  <p><a href="{% url 'editor:detail' pixel.posicao %}">Mudar denovo?</a></p>

  <p><a href="{% url 'editor:index' %}">Voltar pro grid?</a></p>
</main>